tables:
  messages:
    columns:
      id:
        value: VarChar
  images:
    rows:
      id:
        value: NumberI

settings:
  compartment:
    rows: 25 # Amount of rows per db compartment
  password: Thisisastring1
